name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          # Debug the SSH key format
          head -n 5 key.pem

      - name: Print environment variables for debugging
        env:
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "USERNAME: $USERNAME"
          echo "HOST_DNS: $HOST_DNS"
          echo "TARGET_DIR: $TARGET_DIR"

      - name: Test SSH connection
        env:
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh -i key.pem -v -o StrictHostKeyChecking=no $USERNAME@$HOST_DNS "echo 'SSH Connection Successful'"

      - name: Copy files to EC2
        env:
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          rsync -avz -e "ssh -i key.pem -v -o StrictHostKeyChecking=no" ./ $USERNAME@$HOST_DNS:$TARGET_DIR/
